apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  # The deployment detects which pods to control using the 'selector' option 
  # We can matchLabels or we can matchExpressions, but the expressions are
  # more complex than the labels, so we are using labels.
  selector:
    matchLabels:
      # Including 2 or more matching labels means that the deployment will controll
      # only the pods that have the 'app' AND the 'new-sample-label', those pods with
      # only one label or different label values, WILL NOT be controlled by this deployment.
      app: second-app
      new-sample-label: my-new-sample-label
  template:
    metadata:
      labels:
        app: second-app
        new-sample-label: my-new-sample-label
        # ... : ...
    spec:
      containers:
        - name: second-node
          image: kenjiemura/kub-first-app