# This is how you "stack" all the config files into a single configuration file
# To separate the yaml objects (configuration files) you should add --- between them
# To se more detailed information about what is inside each configuration, go to the
# individual configuration files

# It is a good practice to put the services first, because the "listeners" of which resources
# should be monitored will be created first
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    sample-group-label: group-1
spec:
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    sample-group-label: group-1
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [first-app, second-app]}
  template:
    metadata:
      labels:
        app: second-app
        new-sample-label: my-new-sample-label
        # ... : ...
    spec:
      containers:
        - name: second-node
          image: kenjiemura/kub-first-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5