apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    # Remember that 'Service' resource doesn't support matchLabels or matchExpressions
    app: auth
  # The 'type' options are:
    # ClusterIP (default)
    # NodePort
    # LoadBalancer: Exposes the IP to the world and distributes the loads
  type: ClusterIP
  ports:
    - protocol: "TCP"
      # Port exposed to the outside
      port: 80
      # Port inside the container
      targetPort: 80