apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: users
    matchExpressions:
      - {key: app, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kenjiemura/kubernetes-demo-frontend:latest