apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: users
    matchExpressions:
      - {key: app, operator: In, values: [users]}
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kenjiemura/kubernetes-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            # - name: AUTH_ADDRESS
            #   valueFrom:
            #     configMapKeyRef:
            #       # Name of the ConfigMap resource
            #       name: data-store-env
            #       # Which key from that file (environment.yaml) should we use
            #       key: auth-address