version: "3.8"

services:
  server:
    container_name: nginx
    image: "nginx:stable-alpine"
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.php
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    depends_on:
      - php

  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: Dockerfile.composer
    volumes:
      - ./src:/var/www/html

  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.php
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    container_name: node
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html