version: "3.8"

services:
  server:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: dockerfiles
      dockerfile: Dockerfile.php
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    depends_on:
      - php

  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: Dockerfile.composer
    volumes:
      - ./src:/var/www/html

  # laravelArtisan:
  # npm: