apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-api
          image: kenjiemura/kubernetes-aws-tasks:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://kenji:moshimoshi@kubernetes-demo-app.tvcvu.mongodb.net/users?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
      #     volumeMounts:
      #       - name: efs-volume
      #         mountPath: /app/users
      # volumes:
      #   - name: efs-volume
      #     persistentVolumeClaim:
      #       claimName: efs-persistent-volume-claim
